-- MySQL Script generated by MySQL Workbench
-- Sun Jul 16 18:42:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema territorios_saber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema territorios_saber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `territorios_saber` DEFAULT CHARACTER SET utf8 ;
USE `territorios_saber` ;

-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_dispositivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_dispositivo` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_dispositivo` (
  `id_dispositivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(200) NOT NULL,
  `activo` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `ultimo_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_dispositivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_usuario` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `passwd` VARCHAR(128) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `permisos` TEXT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_estado` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_estado` (
  `id_estado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_locacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_locacion` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_locacion` (
  `id_locacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `id_estado` INT UNSIGNED NOT NULL,
  `html_cotenido` TEXT NULL,
  `habiltiado` TINYINT(1) NULL,
  PRIMARY KEY (`id_locacion`),
  INDEX `fk_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `territorios_saber`.`ct_estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_media` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_media` (
  `id_media` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(250) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `id_locacion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_media`),
  INDEX `fk_locacion_idx` (`id_locacion` ASC),
  CONSTRAINT `fk_locacion`
    FOREIGN KEY (`id_locacion`)
    REFERENCES `territorios_saber`.`ct_locacion` (`id_locacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `territorios_saber`.`ct_comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `territorios_saber`.`ct_comentario` ;

CREATE TABLE IF NOT EXISTS `territorios_saber`.`ct_comentario` (
  `id_comentario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comentaro` TEXT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `calificacion` INT(1) NULL DEFAULT 0,
  `id_locacion` INT UNSIGNED NOT NULL,
  `fecha` VARCHAR(45) NOT NULL DEFAULT 'NOW()',
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_locacion_comentario_idx` (`id_locacion` ASC),
  CONSTRAINT `fk_locacion_comentario`
    FOREIGN KEY (`id_locacion`)
    REFERENCES `territorios_saber`.`ct_locacion` (`id_locacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
